### ISSUE TITLE
Couldnot Establish a secure connections in Browser

### ISSUE THREAD

**Issue by bh1r123** [uphold/uphold-sdk-android#61]
Hi There,

I tried to run your sample code on my mobile on click of login it's redirecting to the browser on Browser it says couldn't establish a secure connection. So can you please help me or give me a proper code to run the sample. Please have a look at this screenshot.
![img_3608](https://cloud.githubusercontent.com/assets/12783263/11005852/51144cec-84e6-11e5-835b-20fdb38d98fa.JPG)

**Comment by SandroMachado** [comment]
Hi @bh1r123,

The problem should be related with the TLSv1.2 protocol. Android only has the  TLSv1.2 support enabled by default since API level 20 (Lollipop).
 
We introduced a [PR](https://github.com/uphold/uphold-sdk-android/pull/59) to enable the support on the SDK for Android since API level 16 (Jelly Bean). Unfortunately, to complete the first step of the authorization process the browser also needs to support the protocol TLSv1.2.
 
Can you please install a browser that supports TLSv1.2 like [Chrome](https://play.google.com/store/apps/details?id=com.android.chrome) and test if that solves the issue?

**Comment by bh1r123** [comment]
Het @SandroMachado ,

Thank you, It's working on Chrome.

**Comment by SandroMachado** [comment]
@bh1r123 great. Thanks for the feedback!
